services:
  api:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/api
    command: ["cargo", "watch", "-x", "run"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
